const Wallet = require('ethereumjs-wallet')
const importers = require('ethereumjs-wallet/thirdparty')
const ethUtil = require('ethereumjs-util')

const accountImporter = {

  importAccount (strategy, args) {
    try {
      // 使用的是哪种 import 方法
      const importer = this.strategies[strategy]
      // args就是输入的值，如privateKey或者input, password
      const privateKeyHex = importer.apply(null, args)
      return Promise.resolve(privateKeyHex)
    } catch (e) {
      return Promise.reject(e)
    }
  },

  strategies: {
    /**
     * Private Key 方式导入
     * @param privateKey 私钥
     * @return {String}
     */
    'Private Key': (privateKey) => {
      if (!privateKey) {
        throw new Error('Cannot import an empty key.')
      }

      const prefixed = ethUtil.addHexPrefix(privateKey) // 加入0x前缀
      const buffer = ethUtil.toBuffer(prefixed)

      if (!ethUtil.isValidPrivate(buffer)) {
        throw new Error('Cannot import invalid private key.')
      }

      const stripped = ethUtil.stripHexPrefix(prefixed) // 去掉前缀
      return stripped
    },
    /**
     * JSON File 方式导入
     * @param input
     * @param password
     * @return {String}
     */
    'JSON File': (input, password) => {
      let wallet
      try {
        // https://github.com/ethereumjs/ethereumjs-wallet#thirdparty-api
        // import a wallet generated by EtherWallet
        wallet = importers.fromEtherWallet(input, password)
      } catch (e) {
        console.log('Attempt to import as EtherWallet format failed, trying V3...')
      }

      if (!wallet) {
        // https://github.com/ethereumjs/ethereumjs-wallet#wallet-api
        // import a wallet (Version 3 of the Ethereum wallet format).
        // Set nonStrict true to accept files with mixed-caps.
        wallet = Wallet.fromV3(input, password, true)
      }

      return walletToPrivateKey(wallet)
    },
  },

}

function walletToPrivateKey (wallet) {
  // https://github.com/ethereumjs/ethereumjs-wallet#wallet-api
  // getPrivateKey() - return the private key
  const privateKeyBuffer = wallet.getPrivateKey()
  return ethUtil.bufferToHex(privateKeyBuffer)
}

module.exports = accountImporter
